# docker-compose.yml
services:
  django:
    container_name: lms_app
    image: simplelms-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8003:8000"
    depends_on:
      - postgres
    environment:
      PYTHONUNBUFFERED: 1

  postgres:
    container_name: lms_db
    image: postgres:latest
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    ports:
      - "5535:5432"
    volumes:
      - lms_db_data:/var/lib/postgresql/data

volumes:
  lms_db_data:
